theme: minima
title: i am awesome
author: beautidata
email: 
description: > # this means to ignore newlines until "baseurl:"
  in case you were wondering, i am awesome.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  beautidata # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
